In [3]:
import torch 

x = torch.randn(3,requires_grad=True)

#  Forward
# ---------->
y = x + 2

z = y * y * 2

z = z.mean()




#  Backword: Calculate gradients

# This needs to be a scalar or the backward won't work correctly
print("(escalar) Z:",z)
z.backward()

print("Gradient:",x.grad)

Z: tensor(10.2158, grad_fn=<MeanBackward0>)
Gradient: tensor([1.7188, 2.4932, 4.2511])


# Updating W and b

When updating the W you odn't want to add this operations to the grad,
so you need to deactivate this property when doing something like this

In [ ]:
# To deactivate temporarly
x.requires_grad_(False)

# To create a copy without this property
y = x.detach()

In [7]:
# Basic example

weights = torch.ones(4,requires_grad=True)

for e in range(4):
    model_output = (weights * 3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    # You need to reset the grad
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
# The same using an optimizer

weights = torch.ones(4,requires_grad=True)

optimizer = torch.optim.SGD(weights,lr=0.01)
optimizer.step()
optimizer.zero_grad()